"""
report_generator.py - Inspection report generation utilities.

Generates:
  - PDF inspection reports (fpdf2)
  - CSV records (append to shared CSV file)
  - Excel exports (openpyxl)
"""

from __future__ import annotations

import csv
import os
from typing import Any, Dict, List

from fpdf import FPDF


# CSV header columns
CSV_COLUMNS = [
    "capture_id",
    "timestamp",
    "classification",
    "confidence",
    "crack_area",
    "estimated_length",
    "estimated_width",
    "bbox",
    "camera_source",
    "detection_threshold",
    "image_resolution",
]


def generate_pdf_report(
    inspection_data: Dict[str, Any],
    image_path: str,
    overlay_path: str,
    output_path: str,
) -> str:
    """
    Generate a professional PDF inspection report.

    Args:
        inspection_data: dict with inspection metadata
        image_path: path to the original captured image
        overlay_path: path to the segmentation overlay image
        output_path: path where the PDF should be saved

    Returns:
        The output_path on success.
    """
    pdf = FPDF()
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=15)

    # Title
    pdf.set_font("Helvetica", "B", 18)
    pdf.cell(0, 12, "Crack Inspection Report", ln=True, align="C")
    pdf.ln(4)

    # Subtitle with capture ID
    pdf.set_font("Helvetica", "", 11)
    capture_id = inspection_data.get("capture_id", "Unknown")
    pdf.cell(0, 8, f"Capture ID: {capture_id}", ln=True, align="C")
    pdf.ln(8)

    # Metadata table
    pdf.set_font("Helvetica", "B", 12)
    pdf.cell(0, 8, "Inspection Details", ln=True)
    pdf.ln(2)

    pdf.set_font("Helvetica", "", 10)
    fields = [
        ("Timestamp", inspection_data.get("timestamp", "N/A")),
        ("Classification", inspection_data.get("classification", "N/A")),
        ("Confidence", f"{inspection_data.get('confidence', 0):.4f}"),
        ("Crack Area (px)", str(inspection_data.get("crack_area", 0))),
        ("Estimated Length (px)", f"{inspection_data.get('estimated_length', 0):.1f}"),
        ("Estimated Width (px)", f"{inspection_data.get('estimated_width', 0):.1f}"),
        ("Bounding Box", str(inspection_data.get("bbox", "N/A"))),
        ("Camera Source", inspection_data.get("camera_source", "N/A")),
        ("Detection Threshold", str(inspection_data.get("detection_threshold", "N/A"))),
        ("Image Resolution", inspection_data.get("image_resolution", "N/A")),
    ]

    col_width = 60
    for label, value in fields:
        pdf.set_font("Helvetica", "B", 10)
        pdf.cell(col_width, 7, label + ":", border=0)
        pdf.set_font("Helvetica", "", 10)
        pdf.cell(0, 7, str(value), ln=True, border=0)

    pdf.ln(8)

    # Original image
    if os.path.isfile(image_path):
        pdf.set_font("Helvetica", "B", 12)
        pdf.cell(0, 8, "Original Capture", ln=True)
        pdf.ln(2)
        try:
            pdf.image(image_path, w=170)
        except Exception:
            pdf.cell(0, 8, "[Image could not be embedded]", ln=True)
        pdf.ln(6)

    # Overlay image
    if os.path.isfile(overlay_path):
        pdf.set_font("Helvetica", "B", 12)
        pdf.cell(0, 8, "Segmentation Overlay", ln=True)
        pdf.ln(2)
        try:
            pdf.image(overlay_path, w=170)
        except Exception:
            pdf.cell(0, 8, "[Image could not be embedded]", ln=True)
        pdf.ln(6)

    # Footer
    pdf.set_font("Helvetica", "I", 8)
    pdf.cell(
        0, 6,
        "Generated by Matanglawin UAV Crack Inspection System",
        ln=True, align="C",
    )

    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    pdf.output(output_path)
    return output_path


def generate_csv_record(
    inspection_data: Dict[str, Any],
    csv_path: str,
) -> None:
    """
    Append an inspection record as a row to a shared CSV file.

    Creates the CSV with headers if it does not exist.
    """
    file_exists = os.path.isfile(csv_path)
    os.makedirs(os.path.dirname(csv_path), exist_ok=True)

    with open(csv_path, "a", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=CSV_COLUMNS, extrasaction="ignore")
        if not file_exists:
            writer.writeheader()
        writer.writerow(inspection_data)


def generate_excel_export(
    inspections_list: List[Dict[str, Any]],
    output_path: str,
) -> str:
    """
    Generate an Excel workbook from a list of inspection records.

    Args:
        inspections_list: list of inspection dicts
        output_path: path where the .xlsx file should be saved

    Returns:
        The output_path on success.
    """
    from openpyxl import Workbook
    from openpyxl.styles import Font

    wb = Workbook()
    ws = wb.active
    ws.title = "Inspections"

    # Header row
    headers = CSV_COLUMNS + ["image_path", "overlay_path", "report_path"]
    header_font = Font(bold=True)
    for col_idx, header in enumerate(headers, start=1):
        cell = ws.cell(row=1, column=col_idx, value=header)
        cell.font = header_font

    # Data rows
    for row_idx, record in enumerate(inspections_list, start=2):
        for col_idx, header in enumerate(headers, start=1):
            value = record.get(header, "")
            # Convert lists/dicts to string for Excel
            if isinstance(value, (list, dict)):
                value = str(value)
            ws.cell(row=row_idx, column=col_idx, value=value)

    # Auto-width columns (approximate)
    for col_idx, header in enumerate(headers, start=1):
        ws.column_dimensions[
            ws.cell(row=1, column=col_idx).column_letter
        ].width = max(len(header) + 2, 12)

    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    wb.save(output_path)
    return output_path


def generate_excel_export_to_buffer(
    inspections_list: List[Dict[str, Any]],
    buffer,
) -> None:
    """
    Generate an Excel workbook and write it to a file-like buffer (e.g. BytesIO).

    Args:
        inspections_list: list of inspection dicts
        buffer: writable file-like object (e.g. io.BytesIO)
    """
    from openpyxl import Workbook
    from openpyxl.styles import Font

    wb = Workbook()
    ws = wb.active
    ws.title = "Inspections"

    headers = CSV_COLUMNS + ["image_path", "overlay_path", "report_path"]
    header_font = Font(bold=True)
    for col_idx, header in enumerate(headers, start=1):
        cell = ws.cell(row=1, column=col_idx, value=header)
        cell.font = header_font

    for row_idx, record in enumerate(inspections_list, start=2):
        for col_idx, header in enumerate(headers, start=1):
            value = record.get(header, "")
            if isinstance(value, (list, dict)):
                value = str(value)
            ws.cell(row=row_idx, column=col_idx, value=value)

    for col_idx, header in enumerate(headers, start=1):
        ws.column_dimensions[
            ws.cell(row=1, column=col_idx).column_letter
        ].width = max(len(header) + 2, 12)

    wb.save(buffer)


def generate_full_csv_export(
    inspections_list: List[Dict[str, Any]],
    output_path: str,
) -> str:
    """
    Generate a complete CSV export file from a list of inspection records.

    Args:
        inspections_list: list of inspection dicts
        output_path: path where the .csv file should be saved

    Returns:
        The output_path on success.
    """
    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    headers = CSV_COLUMNS + ["image_path", "overlay_path", "report_path"]

    with open(output_path, "w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=headers, extrasaction="ignore")
        writer.writeheader()
        for record in inspections_list:
            writer.writerow(record)

    return output_path
